### ISSUE TITLE
Plugin exception

### ISSUE THREAD

**Issue by gesmit74** [kcl-lang/intellij-kcl-lsp#7]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Just open any project, the error comes up as soon as the LSP is called

### 2. What did you expect to see? (Required)
No errors or exceptions
### 3. What did you see instead (Required)
Exception in plugin KCL-LSP (0.2.1)
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatDirectoryAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl-lsp]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl-lsp]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
### 4. What is your KCL components version? (Required)
Plugin 0.2.1
KCL 0.10.0
KCL-LSP:
kcl-language-server Version: 0.10.0-c020ab3eb4b9179219d6837a57f5d323
Platform: x86_64-unknown-linux-gnu
GitCommit: 181f49596af292760e359f4b47c18a1749895771

**Comment by He1pa** [comment]
This plugin will be deprecated soon. Its function have been migrated to https://plugins.jetbrains.com/plugin/23378-kcl. You can uninstall this plugin.
